export const DEFAULT_CONTROLS: string[] = [
  // ── Documenti / Certificati richiesti ───────────────────────────────────
  "Certificazioni e attestazioni del costruttore (ISO 9001, ISO 14001, ecc.)",
  "Certificati dei materiali – EN 10204 3.1 (virola, fondo, coperchio)",
  "Qualifica procedimenti di saldatura (WPS/PQR)",
  "Qualifica saldatori / operatori (WPQ)",
  "Rapporto verifica spessori / Thickness test report",
  "Esame visivo e dimensionale",
  "Esame visivo saldature",
  "Rugosità interna – dichiarazione + metodo lucidatura",
  "Decappaggio e passivazione – certificato + sostanze utilizzate",
  "Dye check / Liquidi penetranti (LP)",
  "Rapporto NDT (VT, PT, RT, UT, MT)",
  "Prova idraulica – certificato",
  "Prova pneumatica (piastre di rinforzo)",
  "Prova drenaggio e lavaggio",
  "Sistema di lavaggio (sprayballs) – test fluoresceina/riboflavina",
  "Prova funzionale agitatore (ove presente)",
  "Certificato ispezione visiva (SAT/FAT)",
  "Dichiarazione art. 4.3 PED",
  "Dichiarazione CE PED finale dell'apparecchiatura",
  "Dichiarazione \u201C-0,5 bar\u201D (resistenza al vuoto)",
  "Dichiarazione ATEX (se applicabile)",
  "Dichiarazione di incorporazione tipo A (macchina completa)",
  "Dichiarazione di incorporazione tipo B (quasi macchina)",
  "Dichiarazione di prestazione asservimento EN 1090",
  "Dichiarazione di prestazione EN 1090 (DoP)",
  "Dichiarazione MOCA / Food contact",
  "Certificazioni materiali plastici/elastomeri – FDA 21 CFR 177",
  "Conformità alle normative di progettazione utilizzate",
  "Dichiarazione codici di calcolo impiegati",
  "Conformità alla specifica tecnica e al datasheet",
  "Rispondenza al disegno costruttivo",
  "Disegno costruttivo \u201CAs Built\u201D",
  "Corrispondenza con ordine di acquisto",
  "Conformità della fornitura",
  "Conformità alle procedure di fabbricazione",
  "Manuale di istruzioni (uso, installazione, manutenzione)",
  "Elenco connessioni / Connection list",
  "Calibrazioni strumenti",
  "Guarnizioni – dichiarazioni materiali MOCA",
  "Elenco oli lubrificanti e fluidi di servizio",
  "Procedura conservazione attrezzature pre-installazione",
  "Targhetta identificativa – dati obbligatori (verifica)",
  "Presenza accessori – check list",
  "Dichiarazione di installazione a regola d'arte",
  "Imballo e pulizia / Packing and cleaning",
  "Mezzi di sollevamento e carico/scarico / Lifting and loading/unloading equipment",
  "Requisiti di trasporto, mezzi e personale per lo scarico / Transport requirements, vehicles and unloading personnel",
  "Pianificazione spedizione / Shipping planning",
  // ── Ultime righe fisse (sempre selezionate, non disattivabili) ──────────
  "Varie – allegati tecnici",
  "Elenco deviazioni / non conformità",
  "Azioni correttive",
];

/** Etichette degli ultimi 3 controlli che devono SEMPRE essere selezionati. */
export const FINAL_LOCKED_LABELS: ReadonlySet<string> = new Set([
  "Varie – allegati tecnici",
  "Elenco deviazioni / non conformità",
  "Azioni correttive",
]);

