/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as Fase2RouteImport } from './routes/fase2'
import { Route as ControlliRouteImport } from './routes/controlli'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchivioRouteImport } from './routes/archivio'
import { Route as IndexRouteImport } from './routes/index'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const Fase2Route = Fase2RouteImport.update({
  id: '/fase2',
  path: '/fase2',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlliRoute = ControlliRouteImport.update({
  id: '/controlli',
  path: '/controlli',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivioRoute = ArchivioRouteImport.update({
  id: '/archivio',
  path: '/archivio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRoute
  '/auth': typeof AuthRoute
  '/controlli': typeof ControlliRoute
  '/fase2': typeof Fase2Route
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRoute
  '/auth': typeof AuthRoute
  '/controlli': typeof ControlliRoute
  '/fase2': typeof Fase2Route
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRoute
  '/auth': typeof AuthRoute
  '/controlli': typeof ControlliRoute
  '/fase2': typeof Fase2Route
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archivio' | '/auth' | '/controlli' | '/fase2' | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archivio' | '/auth' | '/controlli' | '/fase2' | '/report'
  id:
    | '__root__'
    | '/'
    | '/archivio'
    | '/auth'
    | '/controlli'
    | '/fase2'
    | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivioRoute: typeof ArchivioRoute
  AuthRoute: typeof AuthRoute
  ControlliRoute: typeof ControlliRoute
  Fase2Route: typeof Fase2Route
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fase2': {
      id: '/fase2'
      path: '/fase2'
      fullPath: '/fase2'
      preLoaderRoute: typeof Fase2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlli': {
      id: '/controlli'
      path: '/controlli'
      fullPath: '/controlli'
      preLoaderRoute: typeof ControlliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivio': {
      id: '/archivio'
      path: '/archivio'
      fullPath: '/archivio'
      preLoaderRoute: typeof ArchivioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivioRoute: ArchivioRoute,
  AuthRoute: AuthRoute,
  ControlliRoute: ControlliRoute,
  Fase2Route: Fase2Route,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
