/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ControlliRouteImport } from './routes/controlli'
import { Route as CondizioniRouteImport } from './routes/condizioni'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttivazioneRouteImport } from './routes/attivazione'
import { Route as ArchivioRouteImport } from './routes/archivio'
import { Route as IndexRouteImport } from './routes/index'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlliRoute = ControlliRouteImport.update({
  id: '/controlli',
  path: '/controlli',
  getParentRoute: () => rootRouteImport,
} as any)
const CondizioniRoute = CondizioniRouteImport.update({
  id: '/condizioni',
  path: '/condizioni',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttivazioneRoute = AttivazioneRouteImport.update({
  id: '/attivazione',
  path: '/attivazione',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivioRoute = ArchivioRouteImport.update({
  id: '/archivio',
  path: '/archivio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRoute
  '/attivazione': typeof AttivazioneRoute
  '/auth': typeof AuthRoute
  '/condizioni': typeof CondizioniRoute
  '/controlli': typeof ControlliRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRoute
  '/attivazione': typeof AttivazioneRoute
  '/auth': typeof AuthRoute
  '/condizioni': typeof CondizioniRoute
  '/controlli': typeof ControlliRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRoute
  '/attivazione': typeof AttivazioneRoute
  '/auth': typeof AuthRoute
  '/condizioni': typeof CondizioniRoute
  '/controlli': typeof ControlliRoute
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archivio'
    | '/attivazione'
    | '/auth'
    | '/condizioni'
    | '/controlli'
    | '/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archivio'
    | '/attivazione'
    | '/auth'
    | '/condizioni'
    | '/controlli'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/archivio'
    | '/attivazione'
    | '/auth'
    | '/condizioni'
    | '/controlli'
    | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivioRoute: typeof ArchivioRoute
  AttivazioneRoute: typeof AttivazioneRoute
  AuthRoute: typeof AuthRoute
  CondizioniRoute: typeof CondizioniRoute
  ControlliRoute: typeof ControlliRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlli': {
      id: '/controlli'
      path: '/controlli'
      fullPath: '/controlli'
      preLoaderRoute: typeof ControlliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condizioni': {
      id: '/condizioni'
      path: '/condizioni'
      fullPath: '/condizioni'
      preLoaderRoute: typeof CondizioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attivazione': {
      id: '/attivazione'
      path: '/attivazione'
      fullPath: '/attivazione'
      preLoaderRoute: typeof AttivazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivio': {
      id: '/archivio'
      path: '/archivio'
      fullPath: '/archivio'
      preLoaderRoute: typeof ArchivioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivioRoute: ArchivioRoute,
  AttivazioneRoute: AttivazioneRoute,
  AuthRoute: AuthRoute,
  CondizioniRoute: CondizioniRoute,
  ControlliRoute: ControlliRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
