/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ControlliRouteImport } from './routes/controlli'
import { Route as ArchivioRouteImport } from './routes/archivio'
import { Route as IndexRouteImport } from './routes/index'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlliRoute = ControlliRouteImport.update({
  id: '/controlli',
  path: '/controlli',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivioRoute = ArchivioRouteImport.update({
  id: '/archivio',
  path: '/archivio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRoute
  '/controlli': typeof ControlliRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRoute
  '/controlli': typeof ControlliRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRoute
  '/controlli': typeof ControlliRoute
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archivio' | '/controlli' | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archivio' | '/controlli' | '/report'
  id: '__root__' | '/' | '/archivio' | '/controlli' | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivioRoute: typeof ArchivioRoute
  ControlliRoute: typeof ControlliRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlli': {
      id: '/controlli'
      path: '/controlli'
      fullPath: '/controlli'
      preLoaderRoute: typeof ControlliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivio': {
      id: '/archivio'
      path: '/archivio'
      fullPath: '/archivio'
      preLoaderRoute: typeof ArchivioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivioRoute: ArchivioRoute,
  ControlliRoute: ControlliRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
